# Generated by Django 5.1 on 2024-08-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pass1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='pass2',
            new_name='password2',
        ),
    ]
