# Generated by Django 5.1 on 2024-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_rename_pass1_signup_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password2',
            field=models.CharField(default='', max_length=128),
        ),
    ]
